FROM python:3.11-slim

ENV TRANSFORMERS_OFFLINE=1
ENV HF_HOME='/tmp/hf_home'

WORKDIR app

COPY ./app ./
COPY ./requirements.txt ./

RUN python3.11 -m venv venv \
    && . venv/bin/activate \
    && python3.11 -m pip install --no-cache-dir -r requirements.txt --default-timeout=60

CMD [ "venv/bin/python", "genre_classifier.py" ]